### ISSUE TITLE
How to get Optional<MqttTopic> response topic in @MqttSubscribe annotation

### ISSUE THREAD

**Issue by tksarul** [SmartsquareGmbH/mqtt-starter#12]
I would like to get response topic (may be optional) in subscription.  like below

@MqttSubscribe(topic = "t/a/1", qos = EXACTLY_ONCE)
 public void subscribeAdRequestTopic(String payload, MqttTopic topic, Optional<MqttTopic> responseTopic) {
        log.debug("paylaod: {} in {}, and response to ", payload, topic, responseTopic);
 }

**Comment by rubengees** [comment]
Hi!

The `responseTopic` can not be directly specified in the method signature. Instead, with the latest [0.16.0](https://github.com/SmartsquareGmbH/mqtt-starter/releases/tag/0.16.0) release you could inject the `Mqtt5Publish` and go from there:

```java
@MqttSubscribe(topic = "t/a/1", qos = EXACTLY_ONCE)
public void subscribeAdRequestTopic(Mqtt5Publish message, String payload, MqttTopic topic) {
    Optional<MqttTopic> responseTopic = message.getResponseTopic();

    log.debug("paylaod: {} in {}, and response to ", payload, topic, responseTopic);
}
```

Hope that helps :slightly_smiling_face:

**Comment by tksarul** [comment]
Thanks, This helps lot.
