### ISSUE TITLE
How to not connect when in dev profile

### ISSUE THREAD

**Issue by ohadlahav** [SmartsquareGmbH/mqtt-starter#6]
Hi,

Looking for elegant way to **not** connect to mqtt broker when in dev profile.

Thanks

**Comment by deen13** [comment]
Hey, 

I don't know if this addresses your problem but we @smartsquaregmbh using a local broker in the development phase which is configured in the `application.properties`. During the deployment the `application.properties` gets replaced by another one that contains the credentials for the production broker.

If that workflow don't fit your needs please feel free to create a pull request. Please reach out for us if you have any questions on how to get started. :)

**Comment by rubengees** [comment]
Released in [0.14.0](https://github.com/SmartsquareGmbH/mqtt-starter/releases/tag/0.14.0)!
